version: '3.4'
services:
  web-base:
    build:
      context: ./
      dockerfile: ./docker/phpfpm/Dockerfile
    container_name: web-base
    depends_on:
      - db
    working_dir: "/var/www/"
    volumes:
      - ./docker/phpfpm/php.ini:/etc/php7/conf.d/99-overrides.ini
      - ./:/var/www:delegated
  db:
    image: mysql:5.7
    container_name: db
    environment:
      - MYSQL_ROOT_PASSWORD=password
      - MYSQL_DATABASE=app_db
      - MYSQL_USER=db_user
      - MYSQL_PASSWORD=db_password
    ports:
      - "3306:3306"
  nginx: 
    image: nginx:1.15-alpine
    container_name: nginx
    depends_on:
      - web-base
    volumes:
      - ./:/var/www:delegated
      - ./docker/nginx/dev.conf:/etc/nginx/conf.d/default.conf
      - ./docker/nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./docker/nginx/snippets:/etc/nginx/snippets
      - ./config/nginx/xdebug:/etc/nginx/xdebug
    restart: on-failure
    ports:
      - "443:443"
      - "80:80"